# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-03 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180303_1858'),
        ('tasks', '0002_auto_20180221_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('name', 'project')]),
        ),
    ]
