# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('sorting', models.PositiveSmallIntegerField(verbose_name='Значение сортировки')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('sorting',),
            },
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст заголовка')),
                ('sorting', models.PositiveSmallIntegerField(verbose_name='Значение сортировки')),
                ('items', models.ManyToManyField(to='menu.MenuItem', verbose_name='Пункты этого меню')),
            ],
            options={
                'verbose_name': 'Заголовок меню',
                'verbose_name_plural': 'Заголовки меню',
                'ordering': ('sorting',),
            },
        ),
    ]
