# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmenu',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Position', verbose_name='Должность сотрудника с этим меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='required_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Разрешения для показа пункта меню'),
        ),
    ]
