# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_auto_20180426_1634'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0035_auto_20180424_1811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('then_requested', models.DateField(verbose_name='Когда потребовал')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('responsible', models.ManyToManyField(related_name='BuyRequisition_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные')),
                ('who_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто потребовал')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупки',
            },
        ),
        migrations.CreateModel(
            name='BuyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_date', models.DateField(verbose_name='Дата формирования')),
                ('files', models.ManyToManyField(to='documents.Document')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Задача на закупку',
                'verbose_name_plural': 'Задачи на закупки',
            },
        ),
        migrations.CreateModel(
            name='PositionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер п/п')),
                ('order_date', models.DateField(null=True, verbose_name='Дата заказа')),
                ('expected_delivery_date', models.DateField(null=True, verbose_name='Ожидаемая дата поставки')),
                ('needed_delivery_date', models.DateField(verbose_name='Необходимая дата поставки')),
                ('actual_due_date', models.DateField(null=True, verbose_name='Фактическая дата выполнения')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('buy_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.BuyRequisition', verbose_name='Заявка на закупку')),
                ('buy_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.BuyTask', verbose_name='Задача на закупку')),
                ('canceled_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.PositionRequest', verbose_name='Отмененная позиция')),
                ('good_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodKind', verbose_name='Вид товара')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Заявочная позиция',
                'verbose_name_plural': 'Заявочные позиции',
            },
        ),
    ]
