# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionrequest',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Необходимое количество'),
        ),
    ]
