# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20180427_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrequest',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
