# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20180429_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstask',
            name='work_started',
            field=models.BooleanField(default=False, verbose_name='Не доработана'),
        ),
    ]
