# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_auto_20180427_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticsrequest',
            options={'ordering': ['when_requested'], 'permissions': set([('is_logist', 'Является логистом')]), 'verbose_name': 'Заявка на закупку', 'verbose_name_plural': 'Заявки на закупки'},
        ),
    ]
