# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_logisticstask_work_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticstask',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата формирования'),
        ),
    ]
