# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20180429_1451'),
        ('logistics', '0008_auto_20180430_2242'),
    ]

    operations = [
    ]
