# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_merge_20180501_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrequest',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
