# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0010_auto_20180501_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransferRequest_worker', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
