# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_transferrequest_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferposition',
            name='transferred',
            field=models.IntegerField(null=True, verbose_name='Перемещено'),
        ),
    ]
