# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_transferposition_transferred'),
        ('logistics', '0007_auto_20180503_0959'),
    ]

    operations = [
    ]
