# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_transferposition_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
    ]
