# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_auto_20180504_1315'),
        ('logistics', '0013_transferrequest_completed'),
    ]

    operations = [
    ]
