# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_merge_20180510_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['who_requested'], 'permissions': (('can_work_transfer_request', 'Может брать заявки в работу'),), 'verbose_name': 'Заявка на перемещение', 'verbose_name_plural': 'Заявки на перемещени'},
        ),
    ]
