# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_auto_20180515_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstask',
            name='ready_for_work',
            field=models.BooleanField(default=False, verbose_name='Передана логисту'),
        ),
    ]
