# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_logisticstask_ready_for_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsrequestposition',
            name='delivery_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Срок поставки в рабочих днях'),
        ),
    ]
