# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0020_auto_20180608_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstask',
            name='name',
            field=models.CharField(default='Задача на закупку', max_length=250, verbose_name='Название задачи'),
        ),
    ]
