# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=64, unique=True, verbose_name='Логин')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('work_phone', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Рабочий телефон')),
                ('personal_phone', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='Личный телефон')),
                ('email', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('transportation', models.PositiveSmallIntegerField(default=0, verbose_name='Затраты на проезд')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('healthy', models.BooleanField(default=False, verbose_name='Не курит')),
                ('is_super_user', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('fired', models.BooleanField(default=False, verbose_name='Уволен')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['last_name', 'first_name', 'patronym'],
                'permissions': (('view_full_user', 'Может просматривать полную информацию о сотрудниках'), ('edit_user', 'Может редактировать информацию сотрудников'), ('hire_user', 'Может нанимать сотрудников'), ('fire_user', 'Может увольнять сотрудников')),
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('month', models.DateField(blank=True, null=True)),
                ('counted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_user_added', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
                'permissions': (('view_all_bonus', 'Может просматривать бонусы'),),
            },
        ),
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.FloatField(verbose_name='СМР общее')),
                ('welding', models.FloatField(verbose_name='Навык сварочных работ')),
                ('experience', models.FloatField(verbose_name='Опыт работы в компании')),
                ('etech', models.FloatField(verbose_name='Знание основ электротехники')),
                ('schematic', models.FloatField(verbose_name='Чтение схем')),
                ('initiative', models.FloatField(verbose_name='Инициативность')),
                ('discipline', models.FloatField(verbose_name='Дисциплина, прилежность')),
                ('max_hour', models.PositiveIntegerField(verbose_name='Максимальная стоимость часа')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Коэффициенты',
                'verbose_name_plural': 'Коэффициенты',
                'permissions': (('view_all_coefficients', 'Может просматривать и изменять все коэффициенты'), ('view_sub_coefficients', 'Может просматривать и изменять коэффициенты подчиненных')),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCoefficient',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Название')),
                ('description', models.CharField(max_length=350, verbose_name='Описание')),
                ('value', models.FloatField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Глобальный коэффициент',
                'verbose_name_plural': 'Глобальные коэффициенты',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Зарплата, руб')),
                ('base', models.PositiveIntegerField(verbose_name='По договору, руб')),
                ('advance', models.PositiveIntegerField(verbose_name='Аванс, руб')),
                ('fraction', models.PositiveSmallIntegerField(default=100, verbose_name='Ставка, %')),
                ('by_hours', models.BooleanField(default=True, verbose_name='Почасовая оплата')),
                ('hire_date', models.DateField(verbose_name='Дата приема')),
                ('fire_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата увольнения')),
            ],
            options={
                'verbose_name': 'Занятость',
                'verbose_name_plural': 'Занятости',
                'ordering': ['hire_date', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.Company', verbose_name='компания')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='разрешения')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='occupation',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Position'),
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(to='users.Occupation'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('name', 'company')]),
        ),
    ]
