# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficients',
            name='max_hour',
            field=models.PositiveIntegerField(default=200, verbose_name='Максимальная стоимость часа'),
        ),
    ]
