# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180216_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='installments',
            field=models.IntegerField(default=1, verbose_name='Рассрочка'),
        ),
    ]
