# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180302_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'permissions': (('view_all_bonus', 'Может просматривать бонусы'), ('edit_all_bonuses', 'Может редактировать все бонусы')), 'verbose_name': 'Бонус', 'verbose_name_plural': 'Бонусы'},
        ),
    ]
