# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180405_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_head', to=settings.AUTH_USER_MODEL, verbose_name='Линейный руководитель'),
        ),
    ]
