# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_bonus_cash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'patronym'], 'permissions': (('view_full_user', 'Может просматривать полную информацию о сотрудниках'), ('edit_user', 'Может редактировать информацию сотрудников'), ('hire_user', 'Может нанимать сотрудников'), ('fire_user', 'Может увольнять сотрудников'), ('view_salary', 'Может просматривать з.п.'), ('can_close_salary', 'Может закрывать з.п.'), ('change_hour_prime_cost', 'Может изменять себестоимость человеко/часа'), ('view_warehouse', 'Может просматривать склад')), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
