# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from datetime import datetime
import django.db.models.deletion


def move_content(apps, schema_editor):
	User = apps.get_model('users', 'User')
	Occupation = apps.get_model('users', 'Occupation')
	for user in User.objects.all():
		user.is_superuser = user.is_super_user
		user_occupations = Occupation.objects.filter(user_id=user.id)
		if len(user_occupations):
			user.hire_date = user_occupations[0].hire_date
			user.fire_date = user_occupations[0].fire_date
			for occupation in user_occupations:
				user.positions.add(occupation.position)
		else:
			user.hire_date = datetime(2011, 9, 1)
		user.save()


class Migration(migrations.Migration):
	dependencies = [
		('auth', '0008_alter_user_username_max_length'),
		('users', '0011_user_head'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='coefficients',
			options={'ordering': ('user__last_name', 'user__first_name', 'user__patronym'), 'permissions': (
				('view_all_coefficients', 'Может просматривать и изменять все коэффициенты'),
				('view_sub_coefficients', 'Может просматривать и изменять коэффициенты подчиненных')),
			         'verbose_name': 'Коэффициенты', 'verbose_name_plural': 'Коэффициенты'},
		),
		migrations.AlterModelOptions(
			name='occupation',
			options={'ordering': ('user__last_name', 'user__first_name'), 'verbose_name': 'Занятость',
			         'verbose_name_plural': 'Занятости'},
		),
		migrations.AddField(
			model_name='user',
			name='is_superuser',
			field=models.BooleanField(default=False,
			                          help_text='Designates that this user has all permissions without explicitly assigning them.',
			                          verbose_name='superuser status'),
		),
		migrations.AddField(
			model_name='user',
			name='fire_date',
			field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата увольнения'),
		),
		migrations.AddField(
			model_name='user',
			name='groups',
			field=models.ManyToManyField(blank=True,
			                             help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
			                             related_name='user_set', related_query_name='user', to='auth.Group',
			                             verbose_name='groups'),
		),
		migrations.AddField(
			model_name='user',
			name='hire_date',
			field=models.DateField(default=None, null=True, verbose_name='Дата приема'),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='user',
			name='positions',
			field=models.ManyToManyField(to='users.Position', verbose_name='Должности'),
		),
		migrations.RunPython(
			move_content
		),
		migrations.RemoveField(
			model_name='user',
			name='is_super_user',
		),
		migrations.RemoveField(
			model_name='occupation',
			name='fire_date',
		),
		migrations.RemoveField(
			model_name='occupation',
			name='hire_date',
		),
		migrations.RemoveField(
			model_name='occupation',
			name='position',
		),
		migrations.AddField(
			model_name='user',
			name='user_permissions',
			field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set',
			                             related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
		),
		migrations.AlterField(
			model_name='occupation',
			name='base',
			field=models.PositiveIntegerField(verbose_name='Оклад, руб'),
		),
		migrations.AlterField(
			model_name='occupation',
			name='user',
			field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
			                           verbose_name='Сотрудник'),
		),
		migrations.AlterField(
			model_name='user',
			name='birth_date',
			field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
		),
		migrations.AlterField(
			model_name='user',
			name='hire_date',
			field=models.DateField(verbose_name='Дата приема'),
		),
	]
