# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180116_1346'),
        ('users', '0013_auto_20180407_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='fixed_hour',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Фиксированная стоимость часа'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='main_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Основная компания'),
            preserve_default=False,
        ),
    ]
