# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


def move_transportation(apps, scheme_editor):
	User = apps.get_model('users', 'User')
	Occupation = apps.get_model('users', 'Occupation')
	for user in User.objects.filter(fired=False):
		occupation = Occupation.objects.get(user_id=user.id)
		occupation.transportation = user.transportation
		occupation.save()


class Migration(migrations.Migration):
	dependencies = [
		('users', '0014_auto_20180407_1546'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='occupation',
			options={'ordering': ('user__last_name', 'user__first_name'),
			         'permissions': (('view_occupations', 'Может просматривать ставки'),), 'verbose_name': 'Занятость',
			         'verbose_name_plural': 'Занятости'},
		),
		migrations.AddField(
			model_name='occupation',
			name='transportation',
			field=models.PositiveSmallIntegerField(default=0, verbose_name='Затраты на проезд'),
		),
		migrations.RunPython(
			move_transportation
		),
		migrations.RemoveField(
			model_name='user',
			name='transportation',
		),
	]
