# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180408_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'permissions': (('can_assign_position', 'Может назначать на должности'), ('can_remove_position', 'Может снимать с должностей')), 'verbose_name': 'должность', 'verbose_name_plural': 'должности'},
        ),
    ]
