# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180408_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='main_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.Company', verbose_name='Основная компания'),
        ),
    ]
