# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180411_1709'),
        ('users', '0016_auto_20180411_1113'),
    ]

    operations = [
    ]
