# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps, scheme_editor):
    User = apps.get_model('users', 'User')

    g = Group.objects.create(name='Бухгалтер')
    g.user_set.add(7, 20, 108)

    g = Group.objects.create(name='Ведущий инженер')
    g.user_set.add(3, 22, 29, 37, 55)

    g = Group.objects.create(name='Водитель-экспедитор')
    g.user_set.add(69)

    g = Group.objects.create(name='Генеральный директор')
    g.user_set.add(5)

    g = Group.objects.create(name='Главный инженер')
    g.permissions.add(65, 95, 96, 97, 98, 107, 108, 109, 119)
    g.user_set.add(4)

    g = Group.objects.create(name='Заведующий складом')
    g.permissions.add(107, 108, 110, 111, 112, 114, 116, 117, 118, 119, 120, 121, 149, 155)
    g.user_set.add(33, 120)

    g = Group.objects.create(name='Зам. ГИ по организации производства')

    g = Group.objects.create(name='Зам. ГИ по разработке и внедрению ПО')
    g.user_set.add(2)

    g = Group.objects.create(name='Инженер')
    g.user_set.add(73, 118)

    g = Group.objects.create(name='Инженер-технолог по сварочному производству')
    g.user_set.add(83)

    g = Group.objects.create(name='Инженер I категории')
    g.user_set.add(17, 54, 117, )

    g = Group.objects.create(name='Инженер II категории')
    g.user_set.add(13, 15, 16, 19, 21, 23, 24, 38, 41, 56, 61, 62, 64, 68, 79)

    g = Group.objects.create(name='Инженер III категории')
    g.user_set.add(47, 49, 53, 60, 75, 77, 78, 99, 104, 110, 112, 122, 123)

    g = Group.objects.create(name='Коммерческий директор')
    g.user_set.add(6)

    g = Group.objects.create(name='Мастер')
    g.user_set.add(34, 46, 70, 90)

    g = Group.objects.create(name='Начальник отдела продаж')
    g.user_set.add(97)

    g = Group.objects.create(name='Начальник электромонтажного участка')
    g.permissions.add(31, 32)
    g.user_set.add(26)

    g = Group.objects.create(name='Производитель работ общестроительного участка')
    g.user_set.add(82)

    g = Group.objects.create(name='Производитель работ сварочного участка')
    g.user_set.add(113)

    g = Group.objects.create(name='Руководитель')
    g.user_set.add(95)

    g = Group.objects.create(name='Руководитель коммерческого отдела')
    g.permissions.add(122)
    g.user_set.add(9)

    g = Group.objects.create(name='Руководитель сборочного цеха')
    g.user_set.add(32)

    g = Group.objects.create(name='Системный администратор')
    g.user_set.add(1, 106, 121)

    g = Group.objects.create(name='Специалист коммерческого отдела')
    g.user_set.add(11, 58, 114, 119)

    g = Group.objects.create(name='Специалист коммерческого отдела (логистика)')

    g = Group.objects.create(name='Специалист по охране труда')
    g.user_set.add(18)

    g = Group.objects.create(name='Специалист по персоналу')
    g.permissions.add(39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 81, 82, 83, 84, 85)
    g.user_set.add(45)

    g = Group.objects.create(name='Специалист по планово-экономической работе')
    g.user_set.add(109)

    g = Group.objects.create(name='Экономист')
    g.permissions.add(31, 32, 33, 34, 35, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 81, 82, 83, 84, 85, 99, 100, 123)
    g.user_set.add(8, 27)

    g = Group.objects.create(name='Электрогазосварщик')
    g.user_set.add(87, 100, 102, 111, 115)

    g = Group.objects.create(name='Электромонтажник-наладчик')
    g.user_set.add(12, 25, 28, 30, 36, 51, 59, 63, 65, 66, 71, 72, 74, 76, 80, 81, 89, 91, 92, 93, 96, 105, 107, 116)
    g.user_set.add(88, 103)

    g = Group.objects.create(name='Модераторы видов товаров')
    g.permissions.add(119, 120, 121)
    g.user_set.add(67)

    g = Group.objects.create(name='Просмотр склада')
    g.permissions.add(149)
    g.user_set.add(14, 50, 57)

    g = Group.objects.create(name='Может вносить виды товаров')
    g.permissions.add(119)
    g.user_set.add(31)










class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20180413_1147'),
    ]

    operations = [
        migrations.RunPython(
            create_groups
        )
    ]
