# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180423_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='permissions',
        ),
    ]
