# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_position_permissions'),
        ('users', '0018_user_avatar'),
    ]

    operations = [
    ]
