# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20180426_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Зарплата, руб'),
        ),
    ]
