# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 07:01
from __future__ import unicode_literals

from django.db import migrations, connection


def delete_unit_table(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute("DROP TABLE units_unit;")
    cursor.close()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            delete_unit_table
        )
    ]
