# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_specifications', '0002_specificationspositions_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Утверждён'),
        ),
    ]
