# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_specifications', '0003_specification_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationspositions',
            name='good_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.GoodKind', verbose_name='Вид товара'),
        ),
    ]
