# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_specifications', '0004_auto_20180510_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationspositions',
            name='note',
            field=models.CharField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
