# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товара',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.RemoveField(
            model_name='goodtype',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='good',
            name='good_type',
        ),
        migrations.AlterField(
            model_name='good',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='Склад'),
        ),
        migrations.DeleteModel(
            name='GoodType',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AddField(
            model_name='goodkind',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='good',
            name='good_kind',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodKind', verbose_name='Вид товара'),
            preserve_default=False,
        ),
    ]
