# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20180218_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodkind',
            old_name='article',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='good',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='Склад'),
        ),
    ]
