# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20180221_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='used',
            field=models.BooleanField(default=False, verbose_name='б/у'),
        ),
        migrations.AlterField(
            model_name='good',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='Склад'),
        ),
    ]
