# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20180221_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WareHouse',
            new_name='WarehouseTest',
        ),
    ]
