# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20180226_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarehouseTest',
            new_name='Warehouse',
        ),
    ]
