# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20180226_1625'),
    ]

    operations = [
        migrations.RenameModel("Warehouse", "Location")
    ]
