# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180316_1809'),
        ('warehouse', '0011_auto_20180321_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.GoodGroup', verbose_name='Родительская группа')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='used',
        ),
        migrations.AddField(
            model_name='good',
            name='defect',
            field=models.BooleanField(default=False, verbose_name='Некондиция'),
        ),
        migrations.AddField(
            model_name='good',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='goodkind',
            name='analogs',
            field=models.ManyToManyField(related_name='_goodkind_analogs_+', to='warehouse.GoodKind', verbose_name='Аналоги'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.GoodKind', verbose_name='Вид товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='good',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Location', verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='goodkind',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodkind',
            name='good_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodGroup', verbose_name='Группа товаров'),
        ),
    ]
