# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_auto_20180405_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodkind',
            name='mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса 1 ед. в кг.'),
        ),
        migrations.AddField(
            model_name='goodkind',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип, марка, обозначение документа, опросного листа'),
        ),
        migrations.AlterField(
            model_name='goodkind',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
