# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20180321_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodgroup',
            options={'verbose_name': 'Группа товаров', 'verbose_name_plural': 'Группы товаров'},
        ),
        migrations.AlterField(
            model_name='goodgroup',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.GoodGroup', verbose_name='Родительская группа'),
        ),
    ]
