# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20180330_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип, марка, обозначение документа, опросного листа')),
            ],
            options={
                'verbose_name': 'Товарная позиция',
                'verbose_name_plural': 'Товарные позиции',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressmark', models.CharField(max_length=100, verbose_name='Шифр')),
                ('object_name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('section_name', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('organization', models.CharField(max_length=100, verbose_name='Организация')),
                ('document_name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('state', models.CharField(max_length=100, verbose_name='Стадия')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='SpecificationsPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positional_designation', models.CharField(max_length=100, verbose_name='Позиционное обозночение')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('position_in_table', models.FloatField(verbose_name='Положение в таблице')),
                ('good_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodPosition', verbose_name='Товарная позиция')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Specification', verbose_name='Спецификация')),
            ],
            options={
                'verbose_name': 'Позиция спецификации',
                'verbose_name_plural': 'Позиции спецификаций',
            },
        ),
        migrations.RemoveField(
            model_name='goodkind',
            name='other',
        ),
        migrations.AddField(
            model_name='goodposition',
            name='good_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodKind', verbose_name='Вид товара'),
        ),
    ]
