# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_auto_20180402_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodposition',
            old_name='data_position',
            new_name='description_info',
        ),
    ]
