# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_auto_20180402_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='document_name',
            field=models.CharField(max_length=1000, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='object_name',
            field=models.CharField(max_length=1000, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='section_name',
            field=models.CharField(max_length=1000, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='state',
            field=models.CharField(max_length=10, verbose_name='Стадия'),
        ),
    ]
