# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_auto_20180403_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='arrayData',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=6), null=True, size=3),
        ),
    ]
