# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_specification_arraydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='arrayData',
            new_name='check_list_data',
        ),
    ]
