# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0017_auto_20180328_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='purpose',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AddField(
            model_name='good',
            name='responsible',
            field=models.ForeignKey(default=120, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AlterField(
          model_name='goodkind',
          name='code',
          field=models.CharField(max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
