# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_auto_20180404_1053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodkind',
            unique_together=set([('code', 'manufacturer')]),
        ),
    ]
