# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_auto_20180404_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationspositions',
            name='position_in_table',
            field=models.IntegerField(verbose_name='Положение в таблице'),
        ),
    ]
