# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 11:55
from __future__ import unicode_literals

from django.db import migrations


def strip_name(apps, schema_editor):
    Manufacturer = apps.get_model('warehouse', 'Manufacturer')
    for m in Manufacturer.objects.all():
        m.name = m.name.strip()
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_auto_20180405_1325'),
    ]

    operations = [
        migrations.RunPython(
            strip_name
        )
    ]
