# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_auto_20180405_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationspositions',
            name='grouping_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название группировки'),
        ),
        migrations.AlterField(
            model_name='specificationspositions',
            name='count',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='specificationspositions',
            name='good_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.GoodPosition', verbose_name='Товарная позиция'),
        ),
        migrations.AlterField(
            model_name='specificationspositions',
            name='positional_designation',
            field=models.CharField(max_length=100, null=True, verbose_name='Позиционное обозночение'),
        ),
    ]
