# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 11:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_auto_20180406_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='check_list_data',
        ),
        migrations.AddField(
            model_name='specification',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=4),
        ),
        migrations.AddField(
            model_name='specification',
            name='workers_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
