# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_auto_20180409_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodkind',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул'),
        ),
    ]
