# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20180316_1809'),
        ('warehouse', '0029_auto_20180410_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='editors',
            field=models.ManyToManyField(related_name='_specification_editors_+', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AddField(
            model_name='specification',
            name='project',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='user_created',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
            preserve_default=False,
        ),
    ]
