# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_auto_20180410_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='_specification_editors_+', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
    ]
