# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0033_auto_20180416_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodkind',
            name='default_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ед. измерения по-умолчанию'),
        ),
    ]
