# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0034_goodkind_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodkind',
            options={'permissions': (('can_moderate', 'Может подтверждать виды товаров'),), 'verbose_name': 'Вид товара', 'verbose_name_plural': 'Виды товара'},
        ),
    ]
