# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('warehouse', '0037_auto_20180525_1455'),
	]

	operations = [
		migrations.RunSQL('''
			CREATE INDEX goodkind_name_gin ON warehouse_goodkind USING GIN (to_tsvector('russian', name));
			CREATE INDEX manufacturer_name_gin ON warehouse_manufacturer (to_tsvector('russian', name));
			CREATE INDEX project_specifications_gost_name_gin ON project_specifications_gost USING GIN (to_tsvector('russian', name));
		''')
	]
