# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_auto_20180531_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodkind',
            name='analogs',
            field=models.ManyToManyField(blank=True, to='warehouse.GoodKind', verbose_name='Аналоги'),
        ),
        migrations.AlterField(
            model_name='goodkind',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
