# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_one', models.BooleanField(default=False, verbose_name='Достаточно одного')),
            ],
            options={
                'verbose_name': 'Этап утверждения',
                'verbose_name_plural': 'Этапы утверждения',
                'ordering': ['document'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(verbose_name='Дата утверждения')),
                ('decision', models.NullBooleanField(default=None, verbose_name='Решение')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='documents.Approval', verbose_name='Утверждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Утвердители')),
            ],
            options={
                'verbose_name': 'Утвердитель',
                'verbose_name_plural': 'Утвердители',
                'ordering': ['approval'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('creation_date', models.DateTimeField(verbose_name='Время создания')),
                ('is_real', models.BooleanField(verbose_name='Документ физический')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документа',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type', to='documents.DocumentKind', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='approval',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='documents.Document', verbose_name='Документ'),
        ),
    ]
