# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['id'], 'verbose_name': 'Этап утверждения', 'verbose_name_plural': 'Этапы утверждения'},
        ),
        migrations.AlterModelOptions(
            name='approvalusers',
            options={'ordering': ['id'], 'verbose_name': 'Утвердитель', 'verbose_name_plural': 'Утвердители'},
        ),
    ]
