# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20180403_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='approval',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentKind',
        ),
    ]
