# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20180426_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentkind',
            name='eng_name',
            field=models.CharField(default='test', max_length=250, verbose_name='Название на английском'),
            preserve_default=False,
        ),
    ]
