# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentkind_eng_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentkind',
            options={'verbose_name': 'Вид документа', 'verbose_name_plural': 'Виды документов'},
        ),
        migrations.AlterField(
            model_name='document',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.file_directory_path, verbose_name='Файл'),
        ),
    ]
