# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(blank=True, choices=[('W', 'Исполнитель')], max_length=1, null=True, verbose_name='Тип')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Функциональная роль',
                'verbose_name_plural': 'Функциональные роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Места')),
                ('kind', models.CharField(blank=True, choices=[('C', 'По городу'), ('N', 'Нет работы')], max_length=1, null=True, verbose_name='Тип')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(blank=True, choices=[('N', 'Ночные смены')], max_length=1, null=True, verbose_name='Тип')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_edited', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('report_date', models.DateField(verbose_name='Дата')),
                ('task', models.TextField(null=True, verbose_name='Задача')),
                ('time_spent', models.TimeField(verbose_name='Затраченное время')),
                ('time_from', models.TimeField(null=True, verbose_name='С')),
                ('time_to', models.TimeField(null=True, verbose_name='По')),
                ('distance', models.FloatField(null=True, verbose_name='Расстояние')),
                ('car', models.CharField(choices=[('D', 'Служебный'), ('P', 'Личный')], max_length=1, null=True, verbose_name='Автомобиль')),
                ('gas', models.CharField(choices=[('D', 'Служебный'), ('P', 'Личный')], max_length=1, null=True, verbose_name='Бензин')),
                ('where_from', models.CharField(max_length=150, null=True, verbose_name='Адрес отправления')),
                ('where_to', models.CharField(max_length=150, null=True, verbose_name='Адрес назначения')),
                ('money_spent', models.PositiveSmallIntegerField(null=True, verbose_name='Денег затрачено')),
                ('time_checked', models.DateTimeField(null=True, verbose_name='Время проверки')),
                ('quality_grade', models.PositiveSmallIntegerField(null=True, verbose_name='Оценка качества')),
                ('time_grade', models.PositiveSmallIntegerField(null=True, verbose_name='Оценка срока')),
                ('vc_project', models.PositiveSmallIntegerField(null=True)),
                ('vc_digits', models.PositiveSmallIntegerField(null=True)),
                ('vc_digits_minor', models.PositiveSmallIntegerField(null=True)),
                ('model', models.CharField(max_length=255, null=True, verbose_name='Модель')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('exported', models.PositiveSmallIntegerField(default=0, verbose_name='Экспортирован')),
                ('record_counted', models.PositiveSmallIntegerField(default=0)),
                ('day_off_call', models.BooleanField(default=False)),
                ('night_shift', models.BooleanField(default=False)),
                ('responsible_work_paid', models.BooleanField(default=False)),
                ('night_shifts_paid', models.BooleanField(default=False)),
                ('checked_hr', models.BooleanField(default=False, verbose_name='Проверено Галиной')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('kind', models.CharField(blank=True, choices=[('D', 'Вождение'), ('A', 'Сборка'), ('P', 'Проектирование')], max_length=1, null=True, verbose_name='Тип')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Process', verbose_name='Процесс')),
            ],
            options={
                'verbose_name': 'Подпроцесс',
                'verbose_name_plural': 'Подпроцессы',
                'ordering': ['name'],
            },
        ),
    ]
