# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20171228_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='report',
            name='func_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.FuncRole', verbose_name='Функциональная роль'),
        ),
        migrations.AddField(
            model_name='report',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_place', to='reports.Place', verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='report',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Process', verbose_name='Процесс'),
        ),
        migrations.AddField(
            model_name='report',
            name='projects',
            field=models.ManyToManyField(through='reports.ProjectState', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='report',
            name='sub_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.SubProcess', verbose_name='Подпроцесс'),
        ),
        migrations.AddField(
            model_name='report',
            name='user_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_added', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AddField(
            model_name='report',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_worker', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='projectstate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='projectstate',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.AddField(
            model_name='projectstate',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.State'),
        ),
        migrations.AddField(
            model_name='funcrole',
            name='positions',
            field=models.ManyToManyField(to='users.Position', verbose_name='Должности'),
        ),
    ]
