# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180106_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='car',
            field=models.CharField(blank=True, choices=[('D', 'Служебный'), ('P', 'Личный')], max_length=1, null=True, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='report',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='report',
            name='gas',
            field=models.CharField(blank=True, choices=[('D', 'Служебный'), ('P', 'Личный')], max_length=1, null=True, verbose_name='Бензин'),
        ),
        migrations.AlterField(
            model_name='report',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='report',
            name='money_spent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Денег затрачено'),
        ),
        migrations.AlterField(
            model_name='report',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Process', verbose_name='Процесс'),
        ),
        migrations.AlterField(
            model_name='report',
            name='quality_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка качества'),
        ),
        migrations.AlterField(
            model_name='report',
            name='sub_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.SubProcess', verbose_name='Подпроцесс'),
        ),
        migrations.AlterField(
            model_name='report',
            name='task',
            field=models.TextField(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_checked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время проверки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка срока'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='По'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vc_digits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='vc_digits_minor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='vc_project',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='where_from',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес отправления'),
        ),
        migrations.AlterField(
            model_name='report',
            name='where_to',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес назначения'),
        ),
    ]
