# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20180115_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='kind',
            field=models.CharField(blank=True, choices=[('C', 'По городу'), ('N', 'Нет работы'), ('O', 'Волгоградский офис')], max_length=1, null=True, verbose_name='Тип'),
        ),
    ]
