# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20180124_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние'),
        ),
    ]
