# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20180207_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcrole',
            name='kind',
            field=models.CharField(blank=True, choices=[('W', 'Исполнитель'), ('R', 'Ответственный')], max_length=1, null=True, verbose_name='Тип'),
        ),
    ]
