# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180221_1216'),
        ('reports', '0010_auto_20180210_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.Task', verbose_name='Задачи'),
        ),
    ]
