# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_report_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('global_manage', 'Управление всеми отчетами'), ('change_fields_after_month', 'Изменение записи табеля после закрытия месяца')), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
