# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
