# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_salaryarchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryarchive',
            name='value',
        ),
        migrations.AddField(
            model_name='salaryarchive',
            name='object',
            field=models.BinaryField(default=b'', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
