# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_auto_20180205_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='short',
        ),
        migrations.AddField(
            model_name='dayoff',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='Внесен вручную'),
        ),
    ]
