# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0008_auto_20180212_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoff',
            options={'ordering': ['date'], 'verbose_name': 'Выходной день', 'verbose_name_plural': 'Выходные дни'},
        ),
    ]
