# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0010_auto_20180301_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientsArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('global_coefficients', models.BinaryField(verbose_name='Объект глобальных коэффициентов')),
                ('grade_coefficients', models.BinaryField(verbose_name='Объект оценочных коэффициентов')),
            ],
        ),
    ]
