# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_salarypayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['user__last_name', 'user__first_name', 'company__short_name'], 'permissions': (('can_view_salarypayment', 'Может просматривать выплаты по компаниям'),), 'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
    ]
