# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_auto_20180411_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='advance',
            field=models.PositiveIntegerField(default=0, verbose_name='Аванс'),
            preserve_default=False,
        ),
    ]
