# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 06:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='Название модели')),
                ('instance_id', models.IntegerField(verbose_name='id экземпляра')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('before', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='До')),
                ('after', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='После')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
