# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_logging', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['model'], name='project_log_model_02f690_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['instance_id'], name='project_log_instanc_2fb03d_idx'),
        ),
    ]
