# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ГИП'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.State', verbose_name='Этап проекта'),
        ),
    ]
