# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_auto_20180303_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnalysisSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('filters_schema', models.CharField(max_length=2048, verbose_name='Схема')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Схема фильтра анализа проектов',
                'verbose_name_plural': 'Схемы фильтров анализа проектов',
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectanalysisschema',
            unique_together=set([('user_created', 'name')]),
        ),
    ]
