# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	dependencies = [
		('projects', '0008_auto_20180316_1809'),
		('companies', '0004_client'),
	]

	operations = [
		migrations.AlterField(
			model_name='project',
			name='customer',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Client',
			                        verbose_name='Заказчик'),
		),
	]
