# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180306_1125'),
        ('companies', '0007_auto_20180417_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Заказчик'),
        ),
    ]
