# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now=True)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.TextField(null=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['begin', 'worker__last_name'],
                'permissions': (('change_reason', 'Может изменять причину отсутствия'), ('manage_absences', 'Может редактировать отсутствия')),
            },
        ),
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.AbsenceReason'),
        ),
    ]
