# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(max_length=5, verbose_name='Сокращенное название (аббревиатура)')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('okpo', models.CharField(max_length=8, verbose_name='ОКПО')),
                ('account', models.CharField(max_length=20, verbose_name='Р/С')),
                ('bank', models.CharField(max_length=512, verbose_name='Банк')),
                ('bik', models.CharField(max_length=512, verbose_name='БИК')),
                ('kor_account', models.CharField(max_length=20, verbose_name='К/С')),
            ],
            options={
                'verbose_name': 'реквизиты',
                'verbose_name_plural': 'реквизиты',
                'ordering': ('inn',),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='requisites',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.Requisites', verbose_name='Реквизиты'),
        ),
    ]
