# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models, connection
import django.db.models.deletion


def move_content(apps, schema_editor):
	Company = apps.get_model('companies', 'Company')
	Client = apps.get_model('companies', 'Client')
	max_id = 0
	for company in Company.objects.all():
		Client.objects.create(id=company.id, name=company.name)
		if max_id < company.id:
			max_id = company.id
	# Устанавливаем значение последовательности
	cursor = connection.cursor()
	cursor.execute("SELECT setval(%s, %s, True);", ['companies_client_id_seq', max_id + 1])
	cursor.fetchall()
	cursor.close()


class Migration(migrations.Migration):
	dependencies = [
		('companies', '0003_auto_20180116_1346'),
	]

	operations = [
		migrations.CreateModel(
			name='Client',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
				('requisites',
				 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Requisites',
				                      verbose_name='Реквизиты')),
			],
			options={
				'verbose_name': 'клиент',
				'verbose_name_plural': 'клиенты',
				'ordering': ('name',),
			},
		),
		migrations.RunPython(
			move_content
		),
	]
