# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 09:19
from __future__ import unicode_literals

from django.db import migrations


def delete_old(apps, schema_editor):
	Company = apps.get_model('companies', 'Company')
	Company.objects.filter(requisites__isnull=True).delete()


class Migration(migrations.Migration):
	dependencies = [
		('companies', '0004_client'),
		('projects', '0009_auto_20180306_1125'),
	]

	operations = [
		migrations.RunPython(
			delete_old
		)
	]
