# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20180417_1031'),
        ('projects', '0010_auto_20180416_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='requisites',
        ),
        migrations.AlterField(
            model_name='company',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Client', verbose_name='Контрагент'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Requisites',
        ),
    ]
