# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Полное наименование')),
                ('INN', models.CharField(max_length=100, null=True, verbose_name='ИНН')),
                ('KPP', models.CharField(max_length=100, null=True, verbose_name='КПП')),
                ('OKPO', models.CharField(max_length=100, null=True, verbose_name='Код по ОКПО')),
                ('legal_address', models.CharField(max_length=100, null=True, verbose_name='Юр. адрес')),
                ('street_address', models.CharField(max_length=100, null=True, verbose_name='Фактический адрес')),
                ('phone_number', models.CharField(max_length=100, null=True, verbose_name='Телефон')),
                ('other', models.CharField(max_length=100, null=True, verbose_name='Другое')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('interaction', models.CharField(max_length=1000, verbose_name='Что сделано')),
                ('result', models.CharField(max_length=1000, verbose_name='Результат')),
                ('next_step_date', models.DateField(verbose_name='Дата следующего шага')),
                ('next_step', models.CharField(max_length=1000, verbose_name='Следующий шаг')),
                ('was_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'История взаимодействия',
                'verbose_name_plural': 'Истории взаимодействий',
            },
        ),
        migrations.CreateModel(
            name='ClientHistoryContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ClientHistory')),
            ],
        ),
        migrations.CreateModel(
            name='ClientKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид контрагента',
                'verbose_name_plural': 'Виды контрагентов',
            },
        ),
        migrations.CreateModel(
            name='ClientRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Взаимоотношение',
                'verbose_name_plural': 'Взаимоотношения',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronum', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='Должность')),
                ('phone_number', models.CharField(max_length=100, null=True, verbose_name='Телефон')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AddField(
            model_name='clienthistorycontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Contact'),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='contacts',
            field=models.ManyToManyField(through='clients.ClientHistoryContact', to='clients.Contact', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='client',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ClientKind'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='client',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.ClientRelation'),
        ),
    ]
