# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='OGRN',
            field=models.CharField(max_length=13, null=True, verbose_name='Код по ОГРН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='INN',
            field=models.CharField(max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='KPP',
            field=models.CharField(max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='OKPO',
            field=models.CharField(max_length=8, null=True, verbose_name='Код по ОКПО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='interaction',
            field=models.TextField(verbose_name='Что сделано'),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='next_step',
            field=models.TextField(verbose_name='Следующий шаг'),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='result',
            field=models.TextField(verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='patronum',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
