# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180410_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('view_clients', 'Разрешение на просмотр всех Контрагентов, Клиентов и Истории взаимодействия'),), 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
    ]
