# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20180413_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организационно-правовая форма',
                'verbose_name_plural': 'Организационно-правовые формы',
            },
        ),
    ]
