# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20180426_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': (('view_clients', 'Разрешение на просмотр всех Контрагентов, Клиентов и Истории взаимодействия'),), 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='clienthistory',
            options={'ordering': ['date'], 'verbose_name': 'История взаимодействия', 'verbose_name_plural': 'Истории взаимодействий'},
        ),
        migrations.AlterModelOptions(
            name='clientkind',
            options={'ordering': ['name'], 'verbose_name': 'Вид контрагента', 'verbose_name_plural': 'Виды контрагентов'},
        ),
        migrations.AlterModelOptions(
            name='clientrelation',
            options={'ordering': ['name'], 'verbose_name': 'Взаимоотношение', 'verbose_name_plural': 'Взаимоотношения'},
        ),
        migrations.AlterModelOptions(
            name='organizationform',
            options={'ordering': ['name'], 'verbose_name': 'Организационно-правовая форма', 'verbose_name_plural': 'Организационно-правовые формы'},
        ),
    ]
