# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20180425_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('N', 'Уведомление'), ('S', 'Успешное'), ('W', 'Предупреждение'), ('C', 'Критическое')], default='N', max_length=1, verbose_name='Тип'),
        ),
    ]
